development:
  adapter: postgresql
  encoding: unicode
  database: hartl_sample_app_development
  pool: 5
  username: JConnolly
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: hartl_sample_app_test
  pool: 5
  username: JConnolly
  password:
  host: localhost